# spatial

library(shiny)

load("fittedSTvariogramModels.RData")

# Define UI for miles per gallon application
shinyUI(pageWithSidebar(
  
  # Application title
  headerPanel("Different Spatio-Temporal Variogram Families"),
  
  sidebarPanel("This small shiny app illustrates a couple of different spatio-temporal variogram families as defined in", 
               a("gstat", href="http://cran.r-project.org/web/packages/gstat/index.html", target="_blank"),
               HTML("The sample variogram is calculated from daily mean PM<sub>10</sub>"),
               "concentrations across Germany during the year 2005 (see 'demo(stkrige)' in gstat).",
               "Please direct any comments to", a("Benedikt Gräler", href="http://ifgi.de/graeler/", target="_blank"),".", br(),br(),
               selectInput("family", "Variogram family:", 
                           list("separable cov. model" =  "separable",
                                "product-sum cov. model" = "productSum",
                                "sum-metric cov. model" = "sumMetric",
                                "simple sum-metric cov. model" = "simpleSumMetric",
                                "metric cov. model" = "metric")),
               selectInput("type", "Select plot type:",
                           list("levelplot" = "levelplot",
                                "wireframe" = "wireframe")),
               
               # separable model
               conditionalPanel(condition = "input.family == 'separable'",
                                sliderInput("sep.sill", "spatio-temporal sill:",
                                            min = 0, max = 80, 
                                            value = round(fitSepModel$sill,digits=1), 
                                            step=0.1),
                                sliderInput("sep.space.sill", "spatial sill:",
                                            min = 0.01, max = 1, 
                                            value = round(fitSepModel$space$psill[2],digits=2), 
                                            step=0.01),
                                selectInput("sep.space.fam", "spatial variogram family:",
                                            list("Exp" = "Exp",
                                                 "Sph" = "Sph",
                                                 "Lin" = "Lin"),
                                            selected=fitSepModel$space$model[2]),
                                sliderInput("sep.space.range", "spatial range [km]:",
                                            min = 1, max = 500, 
                                            value = round(fitSepModel$space$range[2],digits=0), 
                                            step=1),
                                
                                sliderInput("sep.time.sill", "temporal sill:",
                                            min = 0.01, max = 1, 
                                            value = round(fitSepModel$time$psill[2],digits=2), 
                                            step=0.01),
                                selectInput("sep.time.fam", "temporal variogram family:",
                                            list("Exp" = "Exp",
                                                 "Sph" = "Sph",
                                                 "Lin" = "Lin"),
                                            selected=fitSepModel$time$model[2]),
                                sliderInput("sep.time.range", "temporal range [days]:",
                                            min = 0.1, max = 20, 
                                            value = round(fitSepModel$time$range[2],digits=1), 
                                            step=0.1)),
               
               # product-sum model
               conditionalPanel(condition = "input.family == 'productSum'",
                                sliderInput("ps.sill", "spatio-temporal sill:",
                                            min = 0, max = 80, 
                                            value = round(fitProdSumModel$sill, digits=1), 
                                            step=0.1),
                                sliderInput("ps.nugget", "spatio-temporal nugget:",
                                            min = 0, max = 80, 
                                            value = round(fitProdSumModel$nugget, digits=1), 
                                            step=0.1),
                                sliderInput("ps.space.sill", "spatial sill:",
                                            min = 0.1, max = 80, 
                                            value = round(fitProdSumModel$space$psill, digits=1), 
                                            step=0.1),
                                selectInput("ps.space.fam", "spatial variogram family:",
                                            list("Exp" = "Exp",
                                                 "Sph" = "Sph",
                                                 "Lin" = "Lin"),
                                            selected=fitProdSumModel$space$model),
                                sliderInput("ps.space.range", "spatial range [km]:",
                                            min = 1, max = 500, 
                                            value = round(fitProdSumModel$space$range, digits=0), 
                                            step=1),
                                
                                sliderInput("ps.time.sill", "temporal sill:",
                                            min = 0.1, max = 80, 
                                            value = round(fitProdSumModel$time$psill, digits=2), 
                                            step=0.1),
                                selectInput("ps.time.fam", "temporal variogram family:",
                                            list("Exp" = "Exp",
                                                 "Sph" = "Sph",
                                                 "Lin" = "Lin"),
                                            selected=fitProdSumModel$time$model),
                                sliderInput("ps.time.range", "temporal range [days]:",
                                            min = 0.1, max = 20, 
                                            value = round(fitProdSumModel$time$range,digits=1), 
                                            step=0.1)),
               
               # sum-metric model
               conditionalPanel(condition = "input.family == 'sumMetric'",
                                sliderInput("sumMetric.stAni", "spatio-temporal anisotropy [km/day]:",
                                            min = 0, max = 200, 
                                            value = round(fitSumMetricModel$stAni, digits=1), 
                                            step=0.1),
                                sliderInput("sumMetric.space.sill", "spatial sill:",
                                            min = 0.1, max = 80, 
                                            value = round(fitSumMetricModel$space$psill[2], digits=1), 
                                            step=0.1),
                                selectInput("sumMetric.space.fam", "spatial variogram family:",
                                            list("Exp" = "Exp",
                                                 "Sph" = "Sph",
                                                 "Lin" = "Lin"),
                                            selected=fitSumMetricModel$space$model[2]),
                                sliderInput("sumMetric.space.range", "spatial range [km]:",
                                            min = 1, max = 500, 
                                            value = round(fitSumMetricModel$space$range[2], digits=0), 
                                            step=1),
                                sliderInput("sumMetric.space.nugget", "spatial nugget:",
                                            min = 0, max = 80, 
                                            value = round(fitSumMetricModel$space$psill[1], digits=1), 
                                            step=0.1),
                                
                                sliderInput("sumMetric.time.sill", "temporal sill:",
                                            min = 0.01, max = 20, 
                                            value = round(fitSumMetricModel$time$psill[2], digits=2), 
                                            step=0.01),
                                selectInput("sumMetric.time.fam", "temporal variogram family:",
                                            list("Exp" = "Exp",
                                                 "Sph" = "Sph",
                                                 "Lin" = "Lin"),
                                            selected=fitSumMetricModel$time$model[2]),
                                sliderInput("sumMetric.time.range", "temporal range [days]:",
                                            min = 1, max = 500, 
                                            value = round(fitSumMetricModel$time$range[2], digits=0), 
                                            step=1),
                                sliderInput("sumMetric.time.nugget", "temporal nugget:",
                                            min = 0, max = 80, 
                                            value = round(fitSumMetricModel$time$psill[1], digits=1), 
                                            step=0.1),
                                
                                sliderInput("sumMetric.joint.sill", "joint sill:",
                                            min = 0.1, max = 80, 
                                            value = round(fitSumMetricModel$joint$psill[2], digits=1), 
                                            step=0.1),
                                selectInput("sumMetric.joint.fam", "joint variogram family:",
                                            list("Exp" = "Exp",
                                                 "Sph" = "Sph",
                                                 "Lin" = "Lin"),
                                            selected=fitSumMetricModel$joint$model[2]),
                                sliderInput("sumMetric.joint.range", "joint range [km]:",
                                            min = 1, max = 500, 
                                            value = round(fitSumMetricModel$joint$range[2], digits=0), 
                                            step=1),
                                sliderInput("sumMetric.joint.nugget", "joint nugget:",
                                            min = 0, max = 80, 
                                            value = round(fitSumMetricModel$joint$psill[1], digits=1), 
                                            step=0.1)),
               
               # simple-sum-metric model
               conditionalPanel(condition = "input.family == 'simpleSumMetric'",
                                sliderInput("simpleSumMetric.stAni", "spatio-temporal anisotropy [km/day]:",
                                            min = 0, max = 200, 
                                            value = round(fitSimpleSumMetricModel$stAni, digits=1), 
                                            step=0.1),
                                sliderInput("simpleSumMetric.nugget", "spatio-temporal nugget:",
                                            min = 0, max = 80, 
                                            value = round(fitSimpleSumMetricModel$nugget, digits=1), 
                                            step=0.1),
                                sliderInput("simpleSumMetric.space.sill", "spatial sill:",
                                            min = 0.1, max = 80, 
                                            value = round(fitSimpleSumMetricModel$space$psill, digits=1), 
                                            step=0.1),
                                selectInput("simpleSumMetric.space.fam", "spatial variogram family:",
                                            list("Exp" = "Exp",
                                                 "Sph" = "Sph",
                                                 "Lin" = "Lin"),
                                            selected=fitSimpleSumMetricModel$space$model),
                                sliderInput("simpleSumMetric.space.range", "spatial range [km]:",
                                            min = 1, max = 500, 
                                            value = round(fitSimpleSumMetricModel$space$range, digits=0), 
                                            step=1),                                
                                
                                sliderInput("simpleSumMetric.time.sill", "temporal sill:",
                                            min = 0.01, max = 20, 
                                            value = round(fitSimpleSumMetricModel$time$psill, digits=2), 
                                            step=0.01),
                                selectInput("simpleSumMetric.time.fam", "temporal variogram family:",
                                            list("Exp" = "Exp",
                                                 "Sph" = "Sph",
                                                 "Lin" = "Lin"),
                                            selected=fitSimpleSumMetricModel$time$model),
                                sliderInput("simpleSumMetric.time.range", "temporal range [days]:",
                                            min = 0.1, max = 20, 
                                            value = round(fitSimpleSumMetricModel$time$range, digits=1), 
                                            step=0.1),
                            
                                sliderInput("simpleSumMetric.joint.sill", "joint sill:",
                                            min = 0.1, max = 80, 
                                            value = round(fitSimpleSumMetricModel$joint$psill, digits=1), 
                                            step=0.1),
                                selectInput("simpleSumMetric.joint.fam", "joint variogram family:",
                                            list("Exp" = "Exp",
                                                 "Sph" = "Sph",
                                                 "Lin" = "Lin"),
                                            selected=fitSimpleSumMetricModel$joint$model),
                                sliderInput("simpleSumMetric.joint.range", "joint range [km]:",
                                            min = 1, max = 500, 
                                            value = round(fitSimpleSumMetricModel$joint$range, digits=0), 
                                            step=1)),
               
               # metric model
               conditionalPanel(condition = "input.family == 'metric'",
                                sliderInput("metric.stAni", "spatio-temporal anisotropy [km/day]:",
                                            min = 0, max = 200, 
                                            value = round(fitMetricModel$stAni, digits=1), 
                                            step=0.1),
                                sliderInput("metric.sill", "joint sill:",
                                            min = 0.1, max = 80, 
                                            value = round(fitMetricModel$joint$psill[2], digits=1), 
                                            step=0.1),
                                selectInput("metric.fam", "joint variogram family:",
                                            list("Exp" = "Exp",
                                                 "Sph" = "Sph",
                                                 "Lin" = "Lin"),
                                            selected=fitMetricModel$joint$model[2]),
                                sliderInput("metric.range", "joint range [km]:",
                                            min = 1, max = 500, 
                                            value = round(fitMetricModel$joint$range[2], digits=0), 
                                            step=1),
                                sliderInput("metric.nugget", "joint nugget:",
                                            min = 0, max = 80, 
                                            value = round(fitMetricModel$joint$psill[1], digits=1), 
                                            step=0.1))
               ),
  
  mainPanel(h2(textOutput("caption")),
            h3(textOutput("valid")),
            plotOutput("vgmPlot"),
#             textOutput("rmse"),
            verbatimTextOutput("model"))  
))